name = "compression-dictionary-test"
main = "./build/server/server.js"

account_id = "9bfdb755def60e50760e33036c6f1624"
compatibility_date = "2024-01-29"

workers_dev = true

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "compression-dictionary-test-assets"
